import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

// We will define SettingsProvider in main.dart or a separate file.
// For now, let's assume it's in main.dart or we'll move it to a proper provider file later.
import '../main.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Journal',
      'home': 'Home',
      'journal': 'Journal',
      'task': 'Task',
      'report': 'Report',
      'setting': 'Setting',
      'todo': 'Todo',
      'note': 'Note',
      'download_share': 'Download Journal now!',
      'app_description':
          'Journal is a custom daily logging app designed to help you track habits, trading, or any activity with fully customizable templates.',
      'font_size_small': 'Small',
      'font_size_medium': 'Medium',
      'font_size_large': 'Large',
      'color_theme': 'Color Theme',
      'fast_actions': 'Fast Actions',
      'pinned_notes': 'Pinned Notes',
      'add_categories_hint': 'Add categories in Journal tab',
      'info_app': 'Info App',
      'appearance': 'Appearance',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'font_style': 'Font Style',
      'font_size': 'Font Size',
      'data_support': 'Data & Support',
      'backup_restore': 'Backup & Restore',
      'rate_app': 'Rate App',
      'share_app': 'Share App',
      'tutorial': 'Tutorial',
      'developer_options': 'Developer Options',
      'version': 'Version',
      'select_font': 'Select Font',
      'search_fonts': 'Search fonts...',
      'popular_fonts': 'Popular Fonts',
      'all_fonts': 'All Fonts',
      'success': 'Success',
      'dummy_data_generated': 'Dummy data generated.',
      'clear_all_data': 'Clear All Data',
      'export_data': 'Export Data (to JSON)',
      'export_subtitle': 'Copy your data as a JSON string',
      'data_copied': 'Data copied to clipboard!',
      'import_data': 'Import Data (from JSON)',
      'import_subtitle': 'Restore data from a JSON string',
      'paste_json': 'Paste JSON string here...',
      'cancel': 'Cancel',
      'import': 'Import',
      'import_success': 'Data imported successfully!',
      'import_error': 'Failed to import data. Please check the JSON format.',
      'my_journals': 'My Journals',
      'search_journals': 'Search journals...',
      'sort_az': 'Sort A-Z',
      'no_journals': 'No journals yet. Create one!',
      'pilih_dari_template': 'Choose from Template',
      'gunakan_template': 'Use existing template',
      'buat_template_baru': 'Create New Template (Custom)',
      'buat_field': 'Create fields as you wish',
      'add_template': 'Add Template',
      'tutorial_guide': 'Tutorial & Guide',
      'priority': 'Priority',
      'simpan_task': 'Save Task',
      'fields': 'Fields',
      'add_field': 'Add Field',
      'type': 'Type: ',
      'succ_kpi': 'Succ. KPI: ',
      'pilih_template_jurnal': 'Choose Journal Template',
      'reports': 'Reports',
      'generate_dummy_data': 'Generate Dummy Data',
      'delete_category': 'Delete Category?',
      'delete': 'Delete',
      'error': 'Error',
    },
    'id': {
      'app_title': 'Journal',
      'home': 'Beranda',
      'journal': 'Jurnal',
      'task': 'Tugas',
      'report': 'Laporan',
      'setting': 'Pengaturan',
      'todo': 'Todo',
      'note': 'Catatan',
      'download_share': 'Unduh Journal sekarang!',
      'app_description':
          'Journal adalah aplikasi pencatatan harian kustom yang dirancang untuk membantu Anda melacak progres habit, trading, atau aktivitas apa pun dengan template yang dapat disesuaikan sepenuhnya.',
      'font_size_small': 'Kecil',
      'font_size_medium': 'Sedang',
      'font_size_large': 'Besar',
      'color_theme': 'Tema Warna',
      'fast_actions': 'Aksi Cepat',
      'pinned_notes': 'Catatan Disematkan',
      'add_categories_hint': 'Tambahkan kategori di tab Jurnal',
      'info_app': 'Info Aplikasi',
      'appearance': 'Tampilan',
      'language': 'Bahasa',
      'dark_mode': 'Mode Gelap',
      'font_style': 'Gaya Huruf',
      'font_size': 'Ukuran Huruf',
      'data_support': 'Data & Dukungan',
      'backup_restore': 'Cadangkan & Pulihkan',
      'rate_app': 'Beri Nilai',
      'share_app': 'Bagikan Aplikasi',
      'tutorial': 'Tutorial',
      'developer_options': 'Opsi Pengembang',
      'version': 'Versi',
      'select_font': 'Pilih Huruf',
      'search_fonts': 'Cari huruf...',
      'popular_fonts': 'Huruf Populer',
      'all_fonts': 'Semua Huruf',
      'success': 'Berhasil',
      'dummy_data_generated': 'Data dummy berhasil dibuat.',
      'clear_all_data': 'Hapus Semua Data',
      'export_data': 'Ekspor Data (ke JSON)',
      'export_subtitle': 'Salin data Anda sebagai string JSON',
      'data_copied': 'Data disalin ke papan klip!',
      'import_data': 'Impor Data (dari JSON)',
      'import_subtitle': 'Pulihkan data dari string JSON',
      'paste_json': 'Tempel string JSON di sini...',
      'cancel': 'Batal',
      'import': 'Impor',
      'import_success': 'Data berhasil diimpor!',
      'import_error': 'Gagal mengimpor data. Silakan periksa format JSON.',
      'my_journals': 'Jurnal Saya',
      'search_journals': 'Cari jurnal...',
      'sort_az': 'Urutkan A-Z',
      'no_journals': 'Belum ada jurnal. Buat satu!',
      'pilih_dari_template': 'Pilih dari Template',
      'gunakan_template': 'Gunakan template yang sudah ada',
      'buat_template_baru': 'Buat Template Baru (Custom)',
      'buat_field': 'Buat field sesuai keinginan Anda',
      'add_template': 'Tambah Template',
      'tutorial_guide': 'Tutorial & Panduan',
      'priority': 'Prioritas',
      'simpan_task': 'Simpan Task',
      'fields': 'Field',
      'add_field': 'Tambah Field',
      'type': 'Tipe: ',
      'succ_kpi': 'KPI Sukses: ',
      'pilih_template_jurnal': 'Pilih Template Jurnal',
      'reports': 'Laporan',
      'generate_dummy_data': 'Buat Data Dummy',
      'delete_category': 'Hapus Kategori?',
      'delete': 'Hapus',
      'error': 'Error',
    },
  };

  static String of(BuildContext context, String key) {
    try {
      final language = Provider.of<SettingsProvider>(context).language;
      return _localizedValues[language]?[key] ??
          _localizedValues['en']?[key] ??
          key;
    } catch (e) {
      // Fallback if provider not found
      return _localizedValues['id']?[key] ?? key;
    }
  }
}
